server {
    listen 9091;
    server_name localhost;

    location / {
        proxy_pass http://localhost:9090;
        auth_basic "Prometheus";
        auth_basic_user_file /etc/nginx/prometheus/.htpasswd;
    }
}